/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Itinerary = IDL.Record({
  'destination' : IDL.Text,
  'duration' : IDL.Text,
  'foodPreference' : IDL.Text,
  'tripType' : IDL.Text,
  'interests' : IDL.Text,
  'createdAt' : IDL.Int,
  'budget' : IDL.Text,
  'generatedPlan' : IDL.Text,
});
export const CreateItinerary = IDL.Record({
  'destination' : IDL.Text,
  'duration' : IDL.Text,
  'foodPreference' : IDL.Text,
  'tripType' : IDL.Text,
  'interests' : IDL.Text,
  'budget' : IDL.Text,
  'generatedPlan' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteItinerary' : IDL.Func([IDL.Nat], [], []),
  'getAllItineraries' : IDL.Func([], [IDL.Vec(Itinerary)], ['query']),
  'getItinerary' : IDL.Func([IDL.Nat], [Itinerary], ['query']),
  'saveItinerary' : IDL.Func([CreateItinerary], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Itinerary = IDL.Record({
    'destination' : IDL.Text,
    'duration' : IDL.Text,
    'foodPreference' : IDL.Text,
    'tripType' : IDL.Text,
    'interests' : IDL.Text,
    'createdAt' : IDL.Int,
    'budget' : IDL.Text,
    'generatedPlan' : IDL.Text,
  });
  const CreateItinerary = IDL.Record({
    'destination' : IDL.Text,
    'duration' : IDL.Text,
    'foodPreference' : IDL.Text,
    'tripType' : IDL.Text,
    'interests' : IDL.Text,
    'budget' : IDL.Text,
    'generatedPlan' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteItinerary' : IDL.Func([IDL.Nat], [], []),
    'getAllItineraries' : IDL.Func([], [IDL.Vec(Itinerary)], ['query']),
    'getItinerary' : IDL.Func([IDL.Nat], [Itinerary], ['query']),
    'saveItinerary' : IDL.Func([CreateItinerary], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };